### ISSUE TITLE
something got broken

### ISSUE THREAD

**Issue by luffyfuture** [mrinx/openshift-httpd-php#1]
run rhc app deploy master
...
php is not installed
compiling php
make:**\* No rule to make target '/tmp/bulid/php-5.6.2/ext/openssl/openssl.c',needed by '
ext/openssl/openssl.lo'.stop
An error occurred executing 'gear deploy'(exit code : 2)
Error message : CLIENT_ERROR:failed to execute action hook 'build' for XXX
for more details about the problem,try running the command again with the '--trace' option

**Comment by mrinx** [comment]
Thanks for taking your time to report the problem. Have you tried to run `rhc app deploy master` again; if yes, was the result the same?

**Comment by mrinx** [comment]
Closing as it's now over a year old.
